FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    git \
    libgomp1 \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app/

RUN pip install --upgrade pip

RUN pip install virny_flow@git+https://github.com/denysgerasymuk799/virny-flow.git

RUN pip install huggingface_hub==0.26.5

COPY ./ /opt/app/
